### ISSUE TITLE
Server group is not removed

### ISSUE THREAD

**Issue by TheChaosToast** [RLNT/sinus-automated-servergroups#17]
Hello everybody,

I think your script is just great. But I have a problem: After a while, I let the script user assign a server group. I have deposited these. For this, however, another server group should be removed. Unfortunately that does not work.

I enter it manually - right click - add server group - then the other server group is removed. I've tried Add and Remove and tried all the settings - but now I'm completely at the end. I hope you still have an idea what I'm doing wrong.

I use the script in the current version with the current Sinusbot. Permissions for the bot are also in place.

best regards

**Comment by DAmNRelentless** [comment]
The description of your problem is pretty weak. It's hard to understand what exactly you have issues with.
A descriptive example would be great.

Also version numbers like "current" are unacceptable. Since we could already use another version internally in our development, you can not assume that your "current" version is the same one as ours.
Also the SinusBot versions highly depends on the OS you are using and since you are not giving any information about that, the word "current" is not used in a good way here.

As stated in the issue template which you decided to delete, this issue will be closed because you didn't fill in required information.
Feel free to open another issue or hop onto the discord server for help.
